In [1]:
import numpy as np
import pandas as pd

In [2]:
df= pd.read_excel('./data/2017.xls', encoding='utf-8')
df.head()

,학교,재학생수(A),실수,수용가능인원(B),기숙사수용률 (C=B/Ax100),1인실 기숙사비,2인실 기숙사비,3인실 기숙사비,4인실이상 기숙사비,등록금 (D=B)
0,가톨릭대학교 _제2캠퍼스,1602,41,122,7.6,0,229,146,0,8910.0
1,건국대학교 _본교,17844,1728,3309,18.5,585,382,0,0,8192.3
2,경희대학교 _본교,28736,2509,5547,19.3,316,298,225,101,7804.8
3,고려대학교 _본교,26754,1281,2751,10.3,484,383,208,0,8256.9
4,광운대학교 _본교,8805,32,160,1.8,0,0,0,103,7807.9

In [3]:
# dormi.columns[(index)]

In [4]:
a=dormi[1:2]

NameError: name 'dormi' is not defined

In [5]:
print(list(a))

NameError: name 'a' is not defined

In [6]:
dormi=pd.pivot_table( df, index=['학교'] )
dormi

,1인실 기숙사비,2인실 기숙사비,3인실 기숙사비,4인실이상 기숙사비,기숙사수용률 (C=B/Ax100),등록금 (D=B),수용가능인원(B),실수,재학생수(A)
학교,,,,,,,,,
가톨릭대학교 _제2캠퍼스,0,229,146,0,7.6,8910.0,122,41,1602
건국대학교 _본교,585,382,0,0,18.5,8192.3,3309,1728,17844
경희대학교 _본교,316,298,225,101,19.3,7804.8,5547,2509,28736
고려대학교 _본교,484,383,208,0,10.3,8256.9,2751,1281,26754
광운대학교 _본교,0,0,0,103,1.8,7807.9,160,32,8805
국민대학교 _본교,0,239,193,189,11.2,7877.7,1825,544,16349
덕성여자대학교 _본교,290,220,0,235,13.2,7072.2,779,439,5913
동국대학교 _본교,478,338,0,148,9.0,7939.2,1419,685,15764
동덕여자대학교 _본교,0,304,0,228,3.8,7387.3,268,75,6963
명지대학교 _제2캠퍼스,0,325,0,236,11.7,6905.0,862,305,7365
삼육대학교 _본교,254,0,0,121,12.9,7752.4,766,208,5938
상명대학교 _본교,257,167,216,100,10.7,7652.6,800,215,7500
서강대학교 _본교,0,387,0,180,12.4,7951.5,1222,531,9887
서경대학교 _본교,0,186,0,88,5.9,7812.6,384,104,6523
서울과학기술대학교 _본교,395,206,202,165,14.6,5410.7,1706,686,11658
서울교육대학교 _본교,197,197,0,152,58.0,3088.0,893,339,1539
서울대학교 _본교,245,170,0,153,21.3,6011.4,5933,3070,27875
서울시립대학교 _본교,205,144,0,0,8.0,2390.7,814,521,10153
서울여자대학교 _본교,365,267,0,227,10.6,7515.0,801,311,7539
성공회대학교 _본교,0,98,221,0,6.6,7048.0,149,53,2258
성균관대학교 _본교,407,293,0,152,22.3,8348.4,5371,2756,24068
성신여자대학교 _본교,313,289,287,228,8.4,7735.7,817,323,9716
세종대학교 _본교,122,232,238,195,11.0,7835.0,1403,642,12718
숙명여자대학교 _본교,399,292,321,245,11.0,7971.0,1223,556,11069
숭실대학교 _본교,535,330,200,162,11.4,7919.2,1611,785,14134
연세대학교 _본교,627,308,210,0,35.4,9101.6,9570,4323,27064
이화여자대학교 _본교,402,298,302,217,22.0,8584.5,4284,2426,19475
중앙대학교 _본교,421,342,0,243,12.3,7883.2,2599,1258,21049
총신대학교 _본교,0,94,94,88,51.6,6922.7,1635,411,3171
한국외국어대학교 _본교,466,323,268,185,15.7,7125.4,2940,1415,18674
한성대학교 _본교,160,164,193,204,6.7,7633.7,443,123,6626
한양대학교 _본교,466,257,183,126,12.5,8478.5,2524,1104,20119
홍익대학교 _본교,0,339,167,153,11.4,8254.0,1575,680,13871

In [ ]:
dormi.index

In [ ]:
for name in dormi.index:
    print(name)

In [ ]:
print(dormi.loc[ '가톨릭대학교 _제2캠퍼스' ])
print(list(dormi.loc[ '가톨릭대학교 _제2캠퍼스' ]))